[tool.poetry]
name = "kfin"
version = "0.0.3"
description = ""
authors = ["hyunuck <gusdnr@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
